#!/bin/sh

set -e

choose() {
  printf " [Y/n] "
  read -r reply
  case "$reply" in
    ""|"y"|"Y"|"yes"|"Yes"|"YES")
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

find_command() {
  for command in "$@"; do
    if command -v "$(echo "$command" | awk '{ print $1 }')" > /dev/null; then
      echo "$command"
      return
    fi
  done
  die "none of $*@ were found"
}

die() {
  1>&2 echo "$1"
  exit 1
}

if ! command -v pip3 > /dev/null; then
  python3 -m ensurepip
fi

if ! pip3 show ansible > /dev/null 2>&1; then
  pip3 install ansible
fi

command=$(find_command "curl -sSL" "wget -qO -")
$command https://raw.githubusercontent.com/mtoohey31/dotfiles/main/.ansible/playbooks/requirements.yaml > /tmp/requirements.yaml
ansible-galaxy install -r /tmp/requirements.yaml
rm /tmp/requirements.yaml

playbooks=$($command https://raw.githubusercontent.com/mtoohey31/dotfiles/main/.ansible/playbooks/index)
IFS='
'
for playbook in $playbooks; do
  printf "run playbook %s?" "$playbook"
  if ! choose; then
    continue
  fi
  sh -c "$command https://raw.githubusercontent.com/mtoohey31/dotfiles/main/.ansible/playbooks/$playbook" > "/tmp/$playbook"
 ansible-playbook -i localhost, "/tmp/$playbook" -c local -K
done
