#!/bin/sh

set -e

choose() {
  printf " [Y/n] "
  read -r reply
  case "$reply" in
    ""|"y"|"Y"|"yes"|"Yes"|"YES")
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

find_command() {
  for command in "$@"; do
    if command -v "$(echo "$command" | awk '{ print $1 }')" > /dev/null; then
      echo "$command"
      return
    fi
  done
  die "none of $*@ were found"
}

die() {
  1>&2 echo "$1"
  exit 1
}

username=""

if [ "$(uname)" != "Darwin" ]; then
  printf "create new wheel user?"
  if choose; then
    command=$(find_command "useradd -mG wheel" "adduser -D")
    printf "username: "
    read -r username
    $command "$username"
    passwd "$username"
  else
    printf "user for non-root commands: "
    read -r username
    if ! groups "$username" | grep "wheel" > /dev/null; then
      die "provided user was not in wheel group"
    fi
  fi

  if ! grep '^%wheel ALL=(ALL) ALL$' /etc/sudoers > /dev/null; then
    echo '%wheel ALL=(ALL) ALL' > /etc/sudoers
  fi

  if command -v "apk" > /dev/null; then
    if ! apk info python3-dev sudo --installed > /dev/null; then
      apk add python3-dev sudo
    fi
  elif command -v "pacman" > /dev/null; then
    if ! pacman -Q python sudo > /dev/null 2>&1; then
      pacman -S python sudo
    fi
  else
    die "no supported package manager found"
  fi
fi

if command -v "apk" > /dev/null; then
  if ! apk info gcc musl-dev libffi-dev --installed > /dev/null; then
    apk install "gcc musl-dev libffi-dev"
  fi
fi

command=$(find_command "curl -sSL" "wget -qO -")
# $command "https://raw.githubusercontent.com/mtoohey31/dotfiles/main/.scripts/setup/post-install-user" > /post-user
$command "http://192.168.122.1:8000/post-install-user" > /post-user

chmod 777 /post-user
exec su "$username" -c "cd / && sh post-user"
