---
- name: Setup with my gui configuration
  hosts: all
  vars:
    become_for_packages: "{{ ansible_facts['os_family'] != 'Darwin' }}"
  tasks:
    - name: Install sway
      package:
        name: sway
        state: latest
      become: "{{ become_for_packages }}"
    - name: Install qutebrowser
      package:
        name: qutebrowser
        state: latest
      become: "{{ become_for_packages }}"
    - name: Install qbpm (Archlinux)
      package:
        name: qbpm
        state: latest
      become: "{{ become_for_packages }}"
    # TODO: set up yabai and shkd on MacOS
    # TODO: Set up kitty, qbpm, and harpoond on both
