---
- name: Setup with my gui configuration
  hosts: all
  become_method: su
  vars:
    become_for_packages: "{{ ansible_facts['os_family'] != 'Darwin' }}"
  tasks:
    # TODO: set up yabai and shkd on MacOS
    # TODO: set up bspwm, sxhkd, sway, and window manager on linux
    # TODO: Set up alacritty, qutebrowser, qbpm, and harpoond on both
