#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.8
yabai -m config window_shadow                float

yabai -m config window_border                off
# yabai -m config window_border_width          4
# yabai -m config window_border_radius         4 # Deprecated https://github.com/koekeishiya/yabai/issues/565#issuecomment-642230037
# yabai -m config active_window_border_color   0xff505050
# yabai -m config normal_window_border_color   0xff505050
# yabai -m config insert_window_border_color   0xffd75f5f

yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config layout                       bsp

# yabai -m config top_padding                  16
# yabai -m config bottom_padding               16
# yabai -m config left_padding                 16
# yabai -m config right_padding                16
yabai -m config window_gap                   16

yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^Calculator$" manage=off # For actual calculator app
yabai -m rule --add title="^Calculator$" manage=off # For alacritty R calculator app
yabai -m rule --add title="^qutebrowser Editor$" manage=off # For qutebrowser editor
