#!/usr/bin/env sh

# global settings

yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          4
yabai -m config window_border_radius         4
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff505050
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85
yabai -m config split_ratio                  0.5
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings

yabai -m config layout                       bsp

# yabai -m config top_padding                  60

yabai -m config top_padding                  30
yabai -m config bottom_padding               30
yabai -m config left_padding                 30
yabai -m config right_padding                30
yabai -m config window_gap                   30

# rules

yabai -m rule --add app="^iTerm2$" opacity=1.0
yabai -m rule --add app="^Notion$" opacity=0.9
yabai -m rule --add app="^zoom\.us$" opacity=1.0
yabai -m rule --add title="^.* - YouTube$" opacity=1.0
yabai -m rule --add title="^Picture in Picture$" opacity=1.0

# parallels coherence applications

yabai -m rule --add app="^Overwatch\ Application$" title="^Overwatch$" manage=on

find ~/Library/Parallels/Applications\ Menus/ -maxdepth 3 -type f | awk -F'/' '{ print $NF; }' | awk '{$1=$1};1' | sort | uniq | tr "\n" "\0" | xargs -0 -I{} yabai -m rule --add app="^{}\$" title=".*" manage=on

echo "yabai configuration loaded.."
