#!/usr/bin/env bash

super + Return
    alacritty

super + slash
    alacritty -e fish -C 'lf'

super + space
    rofi -show drun

super + Tab
    rofi -show window

super + c
    bspc rule -a Alacritty -o state=floating && alacritty -e fish -c 'cat ".cache/wal/sequences" && R --quiet --no-save'

super + shift + s
    pkill -USR1 -x sxhkd

super + o
    $HOME/.scripts/switch_output_linux

super + {Down,Up}
    pulsemixer --change-volume {-,+}2

super + shift + {Left,Right,space}
    playerctl --player=spotify {previous,next,play-pause}

super + shift + {Down,Up}
    pulsemixer --id (pulsemixer --list-sinks | grep Spotify | awk '\{ print $4 \}' | sed "s/\,\$//g") --change-volume {-,+}2

{XF86AudioLowerVolume,XF86AudioRaiseVolume}
    pulsemixer --change-volume {-,+}2

{XF86MonBrightnessDown,XF86MonBrightnessUp}
    xbacklight -inc {-,+}10

super + s
    flameshot gui

super + f
    bspc node focused.tiled -t floating || bspc node focused.floating -t tiled

super + shift + f
    bspc node focused.tiled -t fullscreen || bspc node focused.fullscreen -t tiled

super + y
    $HOME/.scripts/random_bg -u

super + d
    sleep 1; xset dpms force off

super + i
    $HOME/.scripts/linein_listen_linux

super + m
    bspc rule -a Alacritty -o state=floating && alacritty -e fish -c 'cat ".cache/wal/sequences" && pulsemixer'

super + b
    bspc node @/ --balance

super + shift + n
    pkill kmonad || fish -c "pgrep kmonad || kmonad $HOME/.config/kmonad/macbook.kbd" &

super + {_,shift + }{h,j,k,l}
    bash -c "COMMAND="{f,s}" && DIR="{west,south,north,east}" && bspc query -N -n \$DIR && bspc node -\$COMMAND \$DIR || bspc monitor -\$COMMAND \$DIR"

super + {1-9,0}
    bspc desktop -f '{1-9,10}'

super + shift + {1-9,0}
    bspc node -d '{1-9,10}' --follow

super + {p,u,g,n}
    qutebrowser-profile --new {personal,university,gaming,mod}

super + shift + {p,u,g,n}
    brave --profile-directory="{Default,Profile 2,Profile 3,Profile 4}"

super + shift + {q,r}
    bspc {quit,wm -r}

super + {w,q}
    bspc node -{c,k}

super + backslash
    bspc node focused.tiled -t fullscreen || bspc node focused.fullscreen -t floating || bspc node focused.floating -t tiled

super + shift + backslash
    bspc node focused.tiled -t floating || bspc node focused.floating -t fullscreen || bspc node focused.fullscreen -t tiled
