#!/usr/bin/env bash

# Programs

alt + Return
    alacritty

alt + slash
    alacritty -e fish -C 'lf'

alt + space
    rofi -show drun

alt + Tab
    rofi -show window

alt + shift + c
    bspc rule -a Alacritty -o state=floating && alacritty -e fish -c 'cat ".cache/wal/sequences" && R --quiet --no-save'

alt + shift + s
    pkill -USR1 -x sxhkd

alt + shift + o
    $HOME/.scripts/switch_output_linux

alt + shift + {Down,Up}
    pulsemixer --change-volume {-,+}2

alt + shift + {Left,Right,space}
    playerctl --player=spotify {previous,next,play-pause}

{XF86AudioLowerVolume,XF86AudioRaiseVolume}
    pulsemixer --change-volume {-,+}2

alt + shift + f
    flameshot gui

alt + shift + w
    $HOME/.scripts/random_bg -u

alt + shift + d
    sleep 1; xset dpms force off

alt + shift + i
    $HOME/.scripts/linein_listen_linux

# BSPWM

alt + shift + b
    bspc node @/ --balance

alt + shift + {_,super + }{h,j,k,l}
    bash -c "COMMAND="{f,s}" && DIR="{west,south,north,east}" && bspc query -N -n \$DIR && bspc node -\$COMMAND \$DIR || bspc monitor -\$COMMAND \$DIR"

alt + shift + {_,super + }{1-9,0}
    bspc {desktop -f,node -d} '^{1-9,10}' --follow

alt + shift + {p,u,g,n}
    $HOME/.scripts/qutebrowser-profile --new {personal,university,gaming,mod}

alt + shift + {q,r}
    bspc {quit,wm -r}

alt + {w,q}
    bspc node -{c,k}

alt + backslash
    bspc node focused.tiled -t fullscreen || bspc node focused.fullscreen -t floating || bspc node focused.floating -t tiled

alt + shift + backslash
    bspc node focused.tiled -t floating || bspc node focused.floating -t fullscreen || bspc node focused.fullscreen -t tiled
