format = """
$username\
$hostname\
$kubernetes\
$directory\
$shlvl\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$lua\
$battery\
$line_break\
$jobs\
$time\
$status\
$shell\
$character"""

[username]
show_always = true
format = "[$user]($style) "

[directory]
format = "in [$path]($style) "

[cmd_duration]
format = "for [$duration]($style) "

[hostname]
style = "bold green"
format = "on [$hostname]($style) "

[character]
success_symbol = "[>](green)"
error_symbol = "[>](red)"
vicmd_symbol = "[<](blue)"

[git_branch]
symbol = ""

[git_commit]
format = "at [$hash]($style) [$tag]($style) "

[git_status]
format = "(with [$all_status$ahead_behind]($style) )"
conflicted = "C"
ahead = "H"
behind = "B"
diverged = "D"
untracked = "U"
stashed = "S"
modified = "M"
staged = "A"
renamed = "R"
deleted = "X"

[shlvl]
format = "at depth [$shlvl]($style) "
disabled = false

[custom.updates]
command = "cat /tmp/num_updates"
shell = "/bin/sh"
format = "with [$output]($style) updates "
when = "test $(cat /tmp/num_updates) -ge 25"

# Nerd Fonts Symbols

[aws]
symbol = " "

[battery]
format = "with [$symbol$percentage]($style) battery "
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

# [git_branch]
# symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "
style = "bold blue"

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
