format = """
$username\
$hostname\
$kubernetes\
$directory\
$shlvl\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$lua\
$battery\
$line_break\
$jobs\
$time\
$status\
$shell\
$character"""

[username]
show_always = true
format = "[$user]($style) "

[cmd_duration]
format = "for [$duration]($style) "

[hostname]
format = "on [$hostname]($style) "

[character]
success_symbol = "[>](blue)"
error_symbol = "[>](red)"
vicmd_symbol = "[<](green)"

[shell]
format = "[$indicator]($style) "
disabled = false

[git_commit]
format = "at [$hash]($style) [$tag]($style)"

[git_status]
format = "(with [$all_status$ahead_behind]($style) )"
conflicted = "UU"
ahead = "A"
behind = "B"
diverged = "V"
untracked = "U"
stashed = "T"
modified = "M"
staged = "S"
renamed = "M"
deleted = "D"

[shlvl]
format = "at depth [$shlvl]($style) "
disabled = false

[custom.updates]
format = "with [$output]($style) updates "
shell = "/bin/sh"
command = "cat /tmp/num_updates"
# TODO: check for recent package manager operations
when = '''if test $(uname) = "Darwin"; then
  update_command="nohup /bin/sh -c \"brew update > /dev/null 2>&1 && brew outdated | wc -l | awk '{ \\\$1 = \\\$1; print }' > /tmp/num_updates\" &"
else
  . /etc/os-release && case "$ID" in
    arch)
      command -v checkupdates > /dev/null 2>&1 || exit 1
      update_command="nohup checkupdates | wc -l > /tmp/num_updates &";;
    alpine)
      update_command="nohup /bin/sh -c \"echo \\\$((\\\$(apk upgrade --simulate | wc -l) - 1)) > /tmp/num_updates\" &";;
    *)
      exit 1;;
  esac
fi
if ! test -e /tmp/num_updates || test -z "$(cat /tmp/num_updates)" || test "$(date -r /tmp/num_updates '+%s')" -lt $(($(date '+%s') - 14400)); then
  eval "$update_command" > /dev/null 2>&1
fi
test "$(cat /tmp/num_updates)" -ge 25'''

[custom.docker]
format = "inside [ ]($style) "
when = "test -f /.dockerenv"

# Nerd Fonts Symbols (https://starship.rs/presets/#nerd-font-symbols)

[aws]
symbol = " "

[battery]
format = "with [$symbol$percentage]($style) battery "
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
format = "in [$path]($style) "
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "
style = "bold blue"

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = "ﯣ "
