#! /usr/bin/env bash

X Configuration

$HOME/.scripts/display_setup

# Recover Wallpaper

$HOME/.fehbg

# Autostart Services

pgrep sxhkd || sxhkd &

pgrep picom || picom &

pgrep rescuetime || rescuetime &

pgrep flashfocus || flashfocus &

imwheel -k -b 45 &

$HOME/.config/polybar/launch.sh &

# bspwm Settings

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DVI-D-0 -d 6 7 8 9
bspc monitor HDMI-0 -s DVI-D-0

bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config top_padding             0
bspc config border_width            0
bspc config window_gap              16
bspc config pointer_modifier        mod1
bspc config pointer_action1         move
bspc config pointer_action2         resize_side

bspc config split_ratio             0.5
bspc config borderless_monocle      false
bspc config gapless_monocle         false

# bspwm Rules

bspc rule -r "*"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled
