#! /usr/bin/env bash

bspc rule -r "*"

sxhkd &

xrandr --output DVI-D-0 --auto --pos 0x0 --output HDMI-0 --pos 1600x-660 --primary
xinput set-prop "Corsair CORSAIR HARPOON RGB WIRELESS Gaming Dongle" "Coordinate Transformation Matrix" 0.1 0 0 0 0.1 0 0 0 1

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DVI-D-0 -d 6 7 8 9
bspc monitor HDMI-0 -s DVI-D-0
# $HOME/.config/polybar/launchboth.sh &

bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true
bspc config top_padding             0
bspc config border_width            0
bspc config window_gap              16
bspc config border_radius           9
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side

bspc config split_ratio             0.5
bspc config borderless_monocle      false
bspc config gapless_monocle         false

bspc rule -a Gimp state=floating follow=on
bspc rule -a Zathura state=tiled
