#!/usr/bin/env sh

wid=$1
class=$2
instance=$3
consequences=$4

primary_monitor_focused=$(bspc query -M -m primary.focused)

if [ -n "$(bspc query -M -m primary.focused)" ] && [ "$(bspc query -N -d $(bspc query -D -n $wid) -n .leaf | wc -l)" -eq "2"  ]; then
  original_ratio=$(bspc config split_ratio)
  bspc config split_ratio 0.333333333333333
  bspc node @/ --equalize
  bspc config split_ratio "$original_ratio"
fi
