#!/bin/sh

if xrandr | grep eDP-1-1; then
  display="eDP-1-1"
else
  display="eDP-1"
fi


if [ "$(cat /sys/class/power_supply/BAT0/status)" != "Discharging" ]; then
  xrandr --output "$display" --mode 2560x1440 --rate 120.00
else
  xrandr --output "$display" --mode 2560x1440 --rate 59.96
fi
