#!/bin/sh

xrandr --output eDP --mode 2560x1440 --pos 2560x1440 --rotate normal --output HDMI-A-0 --off --output DP-1-0.1 --primary --mode 3440x1440 --pos 2560x0 --rotate normal --output DP-1-0.2 --mode 2560x1080 --pos 0x920 --rotate inverted
