#!/bin/sh

xrandr --output eDP --mode 2560x1440 --pos 2560x1440 --rotate normal --output DP-1-0.3 --primary --mode 3440x1440 --pos 2560x0 --rate 120.00 --rotate normal --output DP-1-0.2 --mode 2560x1080 --rate 60.00 --pos 0x920 --rotate inverted
