#!/bin/sh

. ~/.cache/wal/colors-fuzzel

fuzzel --output HDMI-A-1 -x 14 -y 14 -p 14 -w 100 --border-radius=0 --background-color=$background"BF" --text-color=$foreground"FF" --match-color=$color3"FF" --selection-color=$color1"FF" --selection-text-color=$foreground"FF" --border-color="00000000" "$@"
