#!/bin/sh

. ~/.cache/wal/colors-fuzzel

fuzzel --output HDMI-A-1 -x 14 -y 14 -p 14 -w 100 --background-color=$background"FF" --text-color=$foreground"FF" --match-color=$color3"FF" --selection-color=$color8"FF" --selection-text-color=$foreground"FF" "$@"
