#!/usr/bin/env python
import os
from string import Template


def read_template() -> str:
    """Read the template file, which is located in the same direcory as this
    file"""
    with open(os.path.dirname(__file__) + '/fancontrol', 'r') as f:
        return f.read()


def get_name(path: str) -> str:
    """Return the name of hwmon device, given its path."""
    with open(f'{path}/name', 'r') as f:
        return(f.readline().rstrip('\n'))


def write_result(result: str) -> None:
    """Write the resulting fancontrol file."""
    with open("/etc/fancontrol", "w") as f:
        f.write(result)


def main() -> None:
    template = Template(read_template())
    subs_so_far = {}
    if os.path.isdir("/sys/class/hwmon"):
        for hwmon in os.listdir("/sys/class/hwmon"):
            name = get_name(f'/sys/class/hwmon/{hwmon}')
            if name == "corsaircpro":
                subs_so_far["corsaircpro"] = hwmon
                subs_so_far["corsaircpro_dev_path"] = os.path.realpath(
                    f'/sys/class/hwmon/{hwmon}/device').lstrip('/sys/')
            elif name == "coretemp":
                subs_so_far["coretemp"] = hwmon
    write_result(template.substitute(subs_so_far))
    os.system("systemctl restart fancontrol")


if __name__ == '__main__':
    main()
