#!/bin/sh

if xrandr | grep "HDMI-1 connected"; then
  if [ "$(bspc config -m HDMI-1 top_padding)" != "-16" ]; then
    bspc config -m HDMI-1 top_padding -16
    polybar-msg cmd hide
  else
    polybar-msg cmd show
    bspc config -m HDMI-1 top_padding 32
  fi
elif xrandr | grep "DP-0.2" && xrandr | grep "DP-0.3"; then
  if [ "$(bspc config -m %DP-0.3 top_padding)" != "-16" ]; then
    bspc config -m %DP-0.3 top_padding -16
    polybar-msg cmd hide
  else
    polybar-msg cmd show
    bspc config -m %DP-0.3 top_padding 32
  fi
else
  if [ "$(bspc config -m eDP top_padding)" != "-16" ]; then
    bspc config -m eDP top_padding -16
    polybar-msg cmd hide
  else
    polybar-msg cmd show
    bspc config -m eDP top_padding 32
  fi
fi
