#!/usr/bin/env sh

$HOME/.scripts/update_spicetify
xrdb $HOME/.Xresources
which dunst && pkill dunst && $HOME/.config/dunst/launch.sh
ps aux | grep -P -o "(?<=\/.local\/share\/qutebrowser-profiles\/).*\$" | awk '{print $4}' | xargs -I '{}' qbpm launch '{}' ':config-source'
# To install, run `cargo install --git https://github.com/chmln/nvim-ctrl`
nvim-ctrl 'source ~/.config/nvim/init.vim'
$HOME/.config/bspwm/colours
