#!/usr/bin/env sh

$HOME/.scripts/update_spicetify
xrdb $HOME/.Xresources
which dunst && pkill dunst; $HOME/.config/dunst/launch.sh
ps aux | grep -P -o "(?<=\/run\/user\/1000\/qutebrowser\/).*\$" | xargs -t -I '{}' qutebrowser-profile --new '{}' ':config-source'
nvim-ctrl 'source ~/.config/nvim/init.vim'
