#!/usr/bin/fish

cat ".cache/wal/sequences"
eval (echo "bluetoothctl"\n"iwctl"\n"pulsemixer"\n"poweroff"\n"systemctl suspend"\n"supergfxctl -m integrated"\n"supergfxctl -m compute"\n"supergfxctl -m vfio"\n"supergfxctl -m hybrid"\n"supergfxctl -m nvidia" | fzf --color 16)
