#!/usr/bin/env bash

if [[ $1 == "-f" ]]; then
    feh --bg-fill "$(find $HOME/Pictures/Wallpapers/$2 -name '*.png' | sort -R | tail -1)"
    cd $HOME/Pictures/Wallpapers/$2
    git pull --ff origin && git reset --hard
elif [[ $1 == "-u" ]] && [[ -n $2 ]]; then
    wget "https://source.unsplash.com/3840x2160/?$2" -O "$HOME/Pictures/Wallpapers/random/$2.jpeg"
    wal -c
    wal -i "$HOME/Pictures/Wallpapers/random/$2.jpeg"
    $HOME/.scripts/update_spicetify
elif [[ $1 == -u ]]; then
    wget "https://source.unsplash.com/3840x2160/" -O "$HOME/Pictures/Wallpapers/random/random.jpeg"
    wal -c
    wal -i "$HOME/Pictures/Wallpapers/random/random.jpeg"
    $HOME/.scripts/update_spicetify
fi
