#!/bin/fish

cat ".cache/wal/sequences"

function math
    source "$__fish_config_dir/config.fish"

    function math_prompt
        echo -n math
        set_color blue
        echo -n ' > '
        set_color normal
    end

    while read expr -p math_prompt
        builtin math "$expr"
    end
end

set potential_prompts evcxr ghci jshell node python3 R

for prompt in $potential_prompts
    if command -q "$prompt"
        set -a prompts "$prompt"
    end
end

set -a prompts math

eval (string join \n $prompts | fzf --color 16)
