#!/bin/bash

color=$(cat "$HOME/.cache/wal/schemes/$(ls -Art ~/.cache/wal/schemes/ | head -n1)" | jq .colors.color1)

cd .scripts/macos-accent

python3 -c "from macos_accent import set_closest_color; set_closest_color($color)"
