#!/bin/sh

username=$1
hostname=$2
port=$3

echo $username $hostname $port

local_ip=$(ssh $username@$hostname -p $port "/bin/sh -c 'ip addr show \$(ip route show default | awk \'{ print \$5 }\') | grep -Po \'inet \\K[\\d.]+\''" & disown)

if [ -n "$local_ip" ]; then
  ssh -W localhost:22 $username@$local_ip -p $port || ssh -W localhost:22 $username@$hostname -p $port
else
  ssh -W localhost:22 $username@$hostname -p $port
fi
