#!/usr/bin/env bash

liquidctl initialize
for number in {1..6}; do
    /home/mtoohey/.scripts/yoda --match commander control "fan$number" with '(0, 0), (55, 0), (56, 10), (70, 10), (80, 100)' on coretemp.package_id_0 &
done
