#!/bin/bash

if [ $(defaults read com.apple.finder CreateDesktop) != "true" ]; then
    defaults write com.apple.finder CreateDesktop true && killall Finder
else
    defaults write com.apple.finder CreateDesktop false && killall Finder
fi
