#!/usr/bin/env bash

wget $(curl https://api.github.com/repos/home-assistant/IOS/releases/latest | jq --raw-output '[.assets[] | select( .name | contains("mac"))][0].browser_download_url') -O /tmp/home-assistant-mac.zip && unzip -o /tmp/home-assistant-mac.zip -d /tmp/ && osascript -e 'quit app "Home Assistant"' && cp -r /tmp/Home\ Assistant.app /Applications/
