#!/bin/bash

current_date=$(date '+%s')
modification_date=$(date -d "$(grep -P -o "(?<=MetaUpdateTime=\")[\d/: ]+" "$1")" '+%s')
comparison_modification_date="$(($modification_date + 86400))"

if [ "$comparison_modification_date" -lt "$current_date" ]; then
    exit 1
fi
