#!/bin/bash

current_date=$(date '+%s')
modification_date=$(date -j -f '%m/%d/%Y %H:%M:%S' "$(grep -E -o "MetaUpdateTime.{0,100}" "$1" | cut -d '"' -f2)" '+%s')
comparison_modification_date="$(($modification_date + 86400))"

if [ "$comparison_modification_date" -lt "$current_date" ]; then
    exit 1
fi
