#!/usr/bin/env bash

source $HOME/.config/yt_mod_tools/yt_mod_tools.env

bspc desktop -f HDMI-0:^1#next.!occupied

stream_id=$(curl -L -H 'User-Agent: Mozilla' -H 'Cookie: troute=t1;' "https://www.googleapis.com/youtube/v3/search?part=snippet&channelId=$youtube_channel_id&eventType=live&type=video&key=$youtube_v3_api_key" | jq -r .items[0].id.videoId)

brave --new-window --profile-directory="Profile 4" "https://www.youtube.com/watch?v=$stream_id"
brave --new-window --profile-directory="Profile 4" "https://www.youtube.com/live_chat?is_popout=1&v=$stream_id"
brave --new-window --profile-directory="Profile 4" "https://docs.google.com/spreadsheets/u/0/"

sleep 0.5

bspc node @/ --balance

bspc node -f @/1

bspc node -p south

bspc node -o 0.61

brave --new-window --profile-directory="Profile 4" "https://translate.google.com/?sl=auto&tl=en&op=translate"

sleep 0.5

bspc node -f @/2/1

sleep 0.5

xdotool key Tab space

sleep 0.5

xdotool key Tab Tab space

bspc node -f @/2/2

xdotool click 1

bspc node -f @/1

xdotool mousemove_relative -- 0 -10; xdotool mousemove_relative 0 10

xdotool key t
